#include <stdio.h>
#include "../glencrypt.h"


void MP1() {
    FILE *outputf;
    char outputfilename[40];
//    char c = 'A';

    input(Str, "Input name of output text file: ", outputfilename);
    outputf = fopen(outputfilename, "w");
    
//	for(char i = 'A'; i <= 'Z'; i++) {
	for(int i = 0; i < 26; i++) {
		fprintf(outputf, "%c\n", i+65);	
	}
	printf("Program run successfully.\nOutput in %s", outputfilename);
	fclose(outputf);
	return;
}

//Write a program that will read the text stored in the file generated by the program
//in the previous exercise.  User fgetc() for character input.

void MP2() {
    char inputfilename[40];
	char c;
	
    input(Str, "Input name of output text file: ", inputfilename);
	FILE *inputf = fopen(inputfilename, "r");
	
	if (inputf == NULL) {
		printf("ERROR: %s cannot be opened.\n", inputfilename);
		return;
	}
	
	while ((c = fgetc(inputf)) != EOF) {
		printf("%c", c);
	}
	return;
}
