//Write a program that will read the text stored in the file generated by the program
//in the previous exercise.  User fgetc() for character input.

#include <stdio.h>
#include "glencrypt.h"

int main() {
    char inputfilename[40];
	char c;
	
    input(Str, "Input name of output text file: ", inputfilename);
	FILE *inputf = fopen(inputfilename, "r");
	
	if (inputf == NULL) {
		printf("ERROR: %s cannot be opened.\n", inputfilename);
		exit(1);
	}
	
	while ((c = fgetc(inputf)) != EOF) {
		printf("%c", c);
	}
	return 0;
}
